name: tirek_mobile
description: Tirek mobile.

dependencies:
  flutter:
    sdk: flutter
  http: 0.12.1
  shared_preferences: 0.5.8
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/tirek-logo.png
